検索フォーム・コントローラの所得額部分を修正
ToshinoriIzumi/Tokyoto pull request #110
Opened 2023-02-04 18:06 UTC by tsukudakouhei

・conditions_supportモデルで支給額とのアソシエーションが以下1に修正されたため、2に修正
・以下から未満に修正
1. `has_many :incomes, through: :conditions_supports_incomes`
2. `incomes_money_lt`

2023-02-04 23:11 UTC, y-takagiiii commented
LGTMですね

2023-02-10 14:30 UTC, kuuwannya reviewed
@tsukudakouhei income以外のはコメントアウトして@queryにして、seedデータ入れて確認したら動きました。incomeの実装が上手くできてないみたいです。

2023-02-10 14:30 UTC, kuuwannya commented on app/tokyoto_app/app/controllers/top_controller.rb
> +    params[:query][:incomes_money_lt] =
ここから以下をコメントアウトして、`@query`で検索したら問題なく検索はできるけど、incomeの部分が上手く作動しないです。

2023-02-10 15:22 UTC, kuuwannya commented
@tsukudakouhei 
ransackは入力された値に対してどのような挙動をするかでメソッドを判断しないといけないので、今回は`_gt`になるはずです。
例: 200万円未満の所得しか受けれない支援Aが存在する場合、 incomesテーブルに200万が記入される。
`_gt`は入力された数値より大きいレコードを検索する
⇨入力された値が100の場合支援Aは入力された100よりも大きい値なので検索される
https://pikawaka.com/rails/ransack

2023-02-10 15:23 UTC, kuuwannya commented
@tsukudakouhei @y-takagiiii 
修正したので、確認お願いします！

2023-02-11 00:58 UTC, y-takagiiii requested changes
# 確認方法
1. `git checkout -b feature/Fix_SeachForm_#108 origin/feature/Fix_SeachForm_#108`でローカルに落とす
2. `bin/rails db:migrate:reset`、`bin/rails db:seed`
3. サーバー立ち上げてseedデータに入ってるcondition_id 1の支援(入園料補助金)の所得制限(1000000000円)を確認
4. トップページで1100000000(万円)で検索
5. 結果がヒットしないことを確認

# コメント
- `binding.pry`を消してください
-  このブランチのDB設計は合ってますかね？`feature/change_column_database_#105`で修正してるDB設計とずれているとマージ後に動かなそうですけど大丈夫ですかね？

2023-02-11 00:58 UTC, y-takagiiii commented on app/tokyoto_app/app/controllers/top_controller.rb
> +    binding.pry
`binding.pry`消してください！

2023-02-11 02:29 UTC, kuuwannya commented on app/tokyoto_app/app/controllers/top_controller.rb
> +    binding.pry
>トップページで1100000000(万円)で検索

この支援自体は所得制限ないから1億にしたので,1億以下でヒットするかどうかを確認して欲しいかも。
所得制限無しを1億よりもっと大きい額にした方がいいかな？

2023-02-11 02:32 UTC, kuuwannya commented on app/tokyoto_app/app/controllers/top_controller.rb
> +    binding.pry
修正しました。[9667ad6](https://github.com/ToshinoriIzumi/Tokyoto/pull/110/commits/9667ad638e53f69acae8da7d20d4a79251a82622)

2023-02-11 02:34 UTC, kuuwannya commented on app/tokyoto_app/app/controllers/top_controller.rb
> +    binding.pry
>このブランチのDB設計は合ってますかねfeature/change_column_database_#105で修正してるDB設計とずれているとマージ後に動かなそうですけど大丈夫ですかね？

feature/change_column_database_#105を取り込んでいるので、ずれて動かないことはないと思うんですが、どうでしょうか？
DBのブランチが確定してマージされたらそれを取り込んで修正するので、大丈夫かと思います。

2023-02-11 02:34 UTC, kuuwannya commented
@y-takagiiii コメントに関する返信と、修正しました。

2023-02-11 03:59 UTC, kuuwannya commented
@y-takagiiii @ToshinoriIzumi すみません。こちらの方で修正してしまったので、こちらで確認してください。
こちらのブランチにhttps://github.com/ToshinoriIzumi/Tokyoto/pull/110の内容を反映しているため、こちらで作動が確認できる場合、DBのブランチをマージして大丈夫だと思います。

### 確認して欲しいこと
・支援のカラムに「入園」と記入して入園料金補助金（私立幼稚園)の支援が検索できること
・地区のカラムに「台東」と記入して入園料金補助金（私立幼稚園)の支援が検索できること
・お金のカラムに「300」と記入して入園料金補助金（私立幼稚園)の支援が検索できること
・子どもの年齢に「4」と記入して入園料金補助金（私立幼稚園)の支援が検索できること
・入園料金補助金（私立幼稚園)の支援に当てはまらない条件を入れた場合検索結果に何も出てこないこと

・新規登録からプロフィール登録ができること
・プロフィールの編集ができること

2023-02-12 03:24 UTC, y-takagiiii commented
1000(万円)で検索にヒットすること、1000000(万円)で検索にヒットしないことを確認できました。
DBにユーザーの所得額が万円表記で登録されるところは新しいissueで解決しましょうか。
その他の部分は良さそうです。LGTM 👍

2023-02-12 03:25 UTC, y-takagiiii approved these changes

2023-02-12 05:31 UTC, ToshinoriIzumi commented
とりあえず、今回はこれでOKします。
ただ、気になる点があるので、記載します。
1. 一回検索した後に、フォーム未入力で検索をかけた場合に、元の制度が全て表示された状態に戻らない。
2. プロフィール編集が見えずらく、どこからプロフィール修正画面に移動するのかがわからない。
3. プロフィール入力フォームが、子供の年齢のままです。子供の誕生日にした方が良いです。

2023-02-12 05:31 UTC, ToshinoriIzumi commented
LGTM

2023-02-12 05:31 UTC, merged