プライバシーポリシー#101
ToshinoriIzumi/Tokyoto pull request #114
Opened 2023-02-08 13:38 UTC by kashiwagi-rena

2023-02-12 05:32 UTC, kashiwagi-rena commented
プライバシーポリシーの内容がまだ決まっていないため、ページの作成とルーティングのみ作りました！確認よろしくお願いします。

2023-02-12 12:07 UTC, kuuwannya requested changes
フッターにプライバシーポリシーのLinkの部分があるので、そこから遷移できるように実装お願いします。
あと、このブランチって今の最新のdevelopって取り込んでいますか？？
もし取り込んでいなかったら取り込んでおいてください！

2023-02-17 16:47 UTC, kashiwagi-rena commented
ブランチの指示ありがとうございます。
フッターにプライバシーポリシー追加しました！！！
07a3caa

2023-02-18 13:07 UTC, kuuwannya approved these changes

2023-02-18 13:13 UTC, kuuwannya commented
@kashiwagi-rena まだこっちの方は内容決まってないんだよね？？とりあえずOKです！

2023-02-19 01:38 UTC, merged