新DBに合わせたモデルテスト
ToshinoriIzumi/Tokyoto pull request #119
Opened 2023-02-14 07:20 UTC by yuki-sdy

新しいDBに合わせてモデルテストを書きました。
レビューよろしくお願いいたします。

### 確認について
・Dockerコンテナに入って、`bundle exec rspec`を実行して確認お願いします。
・1つだけ上手くいっていないテストがあります、Supportのsupport_nameカラムはuniqueになっているはずなのですが
　同じ名前の制度を作ってもエラーが出ません、こちらの原因についてコメント助言をいただきたいです。
![スクリーンショット 2023-02-14 15 43 13](https://user-images.githubusercontent.com/105707999/218663309-915abc7e-72f3-48fb-870b-3abb58280707.png)

### 留意点
新しいDB作成前にfactrybotを整えたりしていましたが、新DBマージ後は時間の関係上factrybotは使わずテストのみを更新しました。そのため、factrybotの記述は中途半端な感じになっています。

2023-02-15 09:28 UTC, y-takagiiii commented
## 確認手順
1. bin/rails db:migrate:reset
2. bundle exec rspec spec/models
```
An error occurred while loading ./spec/models/condition_spec.rb.
Failure/Error:
  RSpec.describe Condition, type: :model do
    before { @condition = Condition.new }
  
    describe 'validation' do
      it "有効であること" do
        expect(@condition).to be_valid
      end
    end
  end

NameError:
  uninitialized constant Condition
  Did you mean?  ConditionVariable
# ./spec/models/condition_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/models/conditions_supports_incomes_spec.rb.
Failure/Error:
  RSpec.describe ConditionsSupportsIncome, type: :model do
    describe 'validation' do
      before do
        condition = Condition.create
        age = Age.create(
          min: 0,
          max: 20
          )
        support = Support.create(
          support_name: 'support1',

NameError:
  uninitialized constant ConditionsSupportsIncome
# ./spec/models/conditions_supports_incomes_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/models/conditions_supports_status_spec.rb.
Failure/Error:
  RSpec.describe ConditionsSupportsStatus, type: :model do
    describe 'validation' do
      before do
        condition = Condition.create
        status = Status.create(
          status: 'test_status'
        )
        @conditions_supports_status = ConditionsSupportsStatus.new(
          condition_id: condition.id,
          status_id: status.id

NameError:
  uninitialized constant ConditionsSupportsStatus
# ./spec/models/conditions_supports_status_spec.rb:3:in `<top (required)>'

Finished in 0.00003 seconds (files took 10.25 seconds to load)
0 examples, 0 failures, 3 errors occurred outside of examples
```
自分の環境だとテスト3件失敗しちゃってますね…
あと`binding.pry`も使えないのは僕だけ？

2023-02-15 10:02 UTC, yuki-sdy commented
@y-takagiiii 
申し訳ありません…
もう一回ブランチ持ってき直して確認してみていただいてよろしいでしょうか？

あと、binding.pryじゃなくてbyebugだった気が…。

2023-02-15 11:12 UTC, y-takagiiii requested changes
途中までレビューしました。
留意点で書かれているのと、全モデルのテストを書いてもらっているので大変なのは重々承知しているのですが、テストケースが多いのでやはりfactory_botでテストデータを呼び出してもらったほうがいいかと思います。。。

2023-02-15 11:12 UTC, y-takagiiii commented on app/tokyoto_app/spec/models/conditions_support_spec.rb
> +    xit 'condition_idとsupport_idの組み合わせが一意でなければ無効であること' do
`condition_idとsupport_idの組み合わせが一意でなければ無効であること`
このテストケースも要らなそうです！

2023-02-16 07:45 UTC, yuki-sdy commented on app/tokyoto_app/spec/factories/conditions_supports.rb
> +    dependents_num { 1 }
factorybotは全体的に修正します！

2023-02-16 07:45 UTC, yuki-sdy commented on app/tokyoto_app/spec/models/conditions_support_spec.rb
> +    xit 'condition_idとsupport_idの組み合わせが一意でなければ無効であること' do
このテストケースを削除します！

2023-02-16 07:48 UTC, yuki-sdy commented
@y-takagiiii @tsukudakouhei 

改めまして、factorybotでテスト書き直しましたので改めて確認をお願いします。
依然として、supportのsupport_nameはユニークが確認できないままです…。

2023-02-16 07:59 UTC, yuki-sdy commented
あ、すみません。

support.rbで
`validates :support_name, presence: true`のみとなっていたので、
`validates :support_name, presence: true, uniqueness: true`としたら全部テスト通りました！

2023-02-16 10:05 UTC, tsukudakouhei commented
確認しました！！まじ、この数のモデルspec大変ですね。。。感謝しかない！！！
確認観点は、以下になります。
- モデルとschemaで記載されているコードがテストされているか
- テストケース名が、正しいか

確認事項としては、モデルに記載しているscopeテストどうしましょうかね。。。

2023-02-19 03:01 UTC, yuki-sdy commented
### 追加補足
- #126 にてsupports_tagsと命名変更された後を想定して先にテスト側を変更しちゃってます。
- モデルスコープはガワだけ設置してある状態で中身はありません、以後issueを作成して優先順位に応じて追加していく予定です。

2023-02-19 06:20 UTC, y-takagiiii approved these changes

2023-02-19 06:37 UTC, y-takagiiii reviewed
足りてないテストケースだけ追加したら後は良さそうです！

2023-02-19 06:37 UTC, y-takagiiii commented on app/tokyoto_app/spec/models/child_spec.rb
> +
子供の年齢がなければ無効であることもテストしましょうか！

2023-02-19 06:37 UTC, y-takagiiii commented on app/tokyoto_app/spec/models/conditions_support_spec.rb
> +
`payment_limit`と`payment_frequency`のテストもお願いします！

2023-02-19 06:37 UTC, y-takagiiii commented on app/tokyoto_app/spec/models/support_spec.rb
>    end
`publish_state`のテストもお願いします！

2023-02-21 09:50 UTC, yuki-sdy commented
@y-takagiiii 
ありがとうございます。
修正あげますが、指摘いただいた点はよく見ると、それぞれモデルとマイグレーションファイルの記述が異なっておりその辺はこのブランチで修正して良いですかね？

Childのbirth　→　マイグレーションファイルにnull: false無し
Conditions_supportのpayment_limit, payment_frequency　→　マイグレーションファイルはdefault: 0のみnull: falseなし
Supportのpublish_state　→　マイグレーションファイルはnull: falseのみでdefault: 0無し

2023-02-22 13:58 UTC, y-takagiiii commented
> ありがとうございます。
修正あげますが、指摘いただいた点はよく見ると、それぞれモデルとマイグレーションファイルの記述が異なっておりその辺はこのブランチで修正して良いですかね？

Childのbirth　→　マイグレーションファイルにnull: false無し
Conditions_supportのpayment_limit, payment_frequency　→　マイグレーションファイルはdefault: 0のみnull: falseなし
Supportのpublish_state　→　マイグレーションファイルはnull: falseのみでdefault: 0無し

こちらは別ブランチで作業することにします。LGTMです！

2023-02-22 14:02 UTC, merged